### ISSUE TITLE
is it possible to port it to Magento 2

### ISSUE THREAD

**Issue by nelero** [mageprofis/MageProfis_WidgetArray#4]
Hi, this extension is great and really helpful !
i was wondering how to transform it for using in Magento 2 ?
thanks

**Comment by mklooss** [comment]
sorry no

https://github.com/mageprofis/MageProfis_WidgetArray/issues/3

**Comment by riker09** [comment]
Maybe you should add a maintainer notice. "This project is seeking a new maintainer" or "Pull requests for Magento 2 are welcome".
